# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Connect import DataBase

host = "127.0.0.1"
user = "postgres"
password = "123"
db_name = "Homework"

class Ui_InsertWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 217)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 13, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineFam = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFam.setGeometry(QtCore.QRect(70, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineFam.setFont(font)
        self.lineFam.setText("")
        self.lineFam.setObjectName("lineFam")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(240, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 13, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(353, 13, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineOtez = QtWidgets.QLineEdit(self.centralwidget)
        self.lineOtez.setGeometry(QtCore.QRect(400, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineOtez.setFont(font)
        self.lineOtez.setObjectName("lineOtez")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 13, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineStreet = QtWidgets.QLineEdit(self.centralwidget)
        self.lineStreet.setGeometry(QtCore.QRect(580, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineStreet.setFont(font)
        self.lineStreet.setObjectName("lineStreet")
        self.lineDom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDom.setGeometry(QtCore.QRect(70, 75, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineDom.setFont(font)
        self.lineDom.setObjectName("lineDom")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(25, 68, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineDom_k = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDom_k.setGeometry(QtCore.QRect(240, 75, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineDom_k.setFont(font)
        self.lineDom_k.setObjectName("lineFlat")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(175, 68, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineFlat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFlat.setGeometry(QtCore.QRect(400, 75, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lineFlat.setFont(font)
        self.lineFlat.setObjectName("lineFlat")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 68, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.linePhone = QtWidgets.QLineEdit(self.centralwidget)
        self.linePhone.setGeometry(QtCore.QRect(580, 75, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.linePhone.setFont(font)
        self.linePhone.setObjectName("linePhone")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 68, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "fam:"))
        self.label_3.setText(_translate("MainWindow", "name:"))
        self.label_4.setText(_translate("MainWindow", "otez:"))
        self.label_5.setText(_translate("MainWindow", "street:"))
        self.label_2.setText(_translate("MainWindow", "dom:"))
        self.label_6.setText(_translate("MainWindow", "dom_k:"))
        self.label_7.setText(_translate("MainWindow", "flat:"))
        self.label_8.setText(_translate("MainWindow", "phone:"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))

    def add_function(self):
        self.pushButton.clicked.connect(lambda: self.add())

    def add(self):
        add_name = (
            self.lineFam.text(), 
            self.lineName.text(), 
            self.lineOtez.text(), 
            self.lineStreet.text(), 
            self.lineDom.text(), 
            self.lineDom_k.text(), 
            self.lineFlat.text(),
            self.linePhone.text()
            )
        db = DataBase(host, user, password, db_name)
        db.insert(add_name)
        self.close()
        



class InsertWindow(QtWidgets.QMainWindow, Ui_InsertWindow):               # +++
    def __init__(self):
        super(InsertWindow, self).__init__()
        
        self.setupUi(self)
        # self.setWindowTitle('SecondWindow')   
        # self.comboBox.addItems(["Choose a Number", "1", "2", "3", "4"])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_InsertWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
